[package]
name = "update_example_app"
version = "0.1.0"
authors = ["Robert Helmer <rhelmer@rhelmer.org>"]

[dependencies]
spawn-task-port = "0.1.0"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"